### PR TITLE
Consolidate init recipes

### PR DESCRIPTION
**Pull request by notnmeyer**
Hello! There are a few small changes here:

* A new attribute: `node["lita"]["daemon_group"]`. Using a 'nobody' group is technically incorrect, even though you can get away with it sometimes. 'nogroup'' is the correct group to use with the 'nobody' user.

* I threw a guard on including the apt cookbook to only include it for relevant platform families.

* Lastly and the primary reason for this PR: I consolidated the SysV and Runit init recipes into a single recipe. I'm interested in adding CentOS 7 support to the cookbook, which will likely means a systemd service file for managing Lita. The `return` strategy to optionally include those recipes will get messy fast.

I wanted to get your take on consolidating this before I get too deep into the CentOS stuff.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
I'm +1 on this. Thanks for your work!

**Comment by harlanbarnes** [comment]
I'm definitely +1 on this. A took a PR using the return method because the submitter said it was becoming the pattern of choice and I didn't have any info to dispute that. But my preference has been (and was in the original) the way you are doing it now.

One thing, since I DID accept that PR, this is technically a breaking change (in the case that someone was calling the runit_service recipe directly). So I think (based on my limited understanding of semver) we'd have to bump the version to 2.0.0. But it's a relatively small change to do that for.

So I'd like to go two ways: A) we leave a version of runit_service in there that just calls init_service and as a log message with a deprecation notice ... or B) you can roll this up with any changes to support Centos and THAT would feel like a 2.0.0 change. Again, it's possible I'm being too nerdy with the semver. I don't feel that strongly about it, but I thought I'd get your thoughts before I merged/bumped/released.

And thanks for this. I appreciate your work a great deal.

**Comment by jimmycuadra** [comment]
Agreed on the SemVer point actually. It shouldn't block on merging this, but we should block on releasing to the supermarket until we have CentOS support.

**Comment by notnmeyer** [comment]
I'm mostly done with CentOS support, if it's easier we can just do this as one PR.

**Comment by harlanbarnes** [comment]
Either way is fine. One side note, I'm on vacation this week so might be slow to respond.

Again, thanks for all of this work.

**Comment by shortdudey123** [comment]
@notnmeyer any update on the CentOS support?  I would love to be able to use this cookbook on a CentOS host

**Comment by notnmeyer** [comment]
@shortdudey123 My attention at work got pulled somewhere else and I haven't gotten back to working on CentOS support. It's still something I'm planning on getting back to but I don't have much in the way of an update unfortunately.

@harlanbarnes @jimmycuadra Based on your earlier feedback:

> A) we leave a version of runit_service in there that just calls init_service and as a log message with a deprecation notice 

I went ahead and added this. Shouldn't be a breaking change now. How are you feeling about getting this merged?

**Comment by jimmycuadra** [comment]
LGTM

**Comment by harlanbarnes** [comment]
Pulled in the commits, bumped version, added changelog, squashed into a single commit, tagged and released to SuperMarket. Thanks!

**Pull request closed without merging**
