### PR TITLE
Desktophero gem source

### PR DESCRIPTION
**Pull request by desktophero**
Modified the `Gemfile.erb` template to allow a node attribute to drive Gemfile source

There were also some ChefSpec that was failing prior to my changes due to some resources moving to another recipe. I couldn't leave that be.

Only updated README - left CHANGELOG and metadata alone.

Finally, I didn't see any specific rules for contributing back. Fingers crossed this a-okay.

Thanks!

```
Finished in 4.35 seconds (files took 1.48 seconds to load)
19 examples, 0 failures


ChefSpec Coverage report generated...

  Total Resources:   14
  Touched Resources: 11
  Touch Coverage:    78.57%

Untouched Resources:

  execute[chown-openup]              lita/recipes/install.rb:60
  execute[chown-cleanup]             lita/recipes/install.rb:87
  runit_service[lita]                lita/recipes/runit_service.rb:25

Running RuboCop...
Inspecting 19 files
...................

19 files inspected, no offenses detected
```

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Thanks for the contribution! Looks good to me, but I'll wait for Harlan to sign off.

**Comment by desktophero** [comment]
Sounds good. Let me know if anything nor is needed. Thanks!

**Comment by desktophero** [comment]
s/nor/more ... Mobile keyboard :/

**Comment by harlanbarnes** [comment]
This looks great to me too. Thanks for contributing. I'll be bumping the version and releasing to Supermarket shortly.

**Pull request merged**
