### PR TITLE
RHEL Support

### PR DESCRIPTION
**Pull request by MattMencel**
Hi @harlanbarnes,

I just spun up a new CentOS 7.2 Lita server with these changes.  I use rbenv to deploy ruby instead of using the package install, but what's in the PR should work just as well.

Let me know if you want something changed in the PR.

Thanks to @ngtjah who added some of the prelim code for this yesterday.  It was on my plate to do this too.

Thanks!

### CODE REVIEW

**Comment by harlanbarnes** [comment]
Looks great to me. I'm going to add centos7 suite to kitchen and give it a whirl before I release it the Supermarket.

**Comment by harlanbarnes** [comment]
@MattMencel One more question ... are you using the `redis_install_type` of `auto` or handling it yourself your wrapper. I can't get redis installed in Test Kitchen with Centos 7(.1 ... only bento box available) and the redis2 cookbook I'm using.

**Comment by harlanbarnes** [comment]
This was released as part of [1.0.4 to the Supermarket](https://supermarket.chef.io/cookbooks/lita/versions/1.0.4). Thanks so much!

**Comment by MattMencel** [comment]
@harlanbarnes I just used "auto" for the redis_install_type and it worked fine for me.  It was a brand new install of CentOS, fully patched to 7.2.

**Comment by harlanbarnes** [comment]
Great. So it was something up with the redis cookbook and CentOS 7.1 or the bento box itself. Either way, we are probably okay. Thanks for testing that.

**Pull request merged**
