### PR TITLE
add runit support and enable it by default

### PR DESCRIPTION
**Pull request by ptqa**
Related to [this issue](https://github.com/litaio/chef-lita/issues/8). Worked for me. 

Also you can disable runit by setting ['lita']['runit']['enabled'] = false

### CODE REVIEW

**Comment by harlanbarnes** [comment]
Hi there!

Thanks so much for contributing this! I have only one general comment that I'd like your feedback on. Given that we have the SysV init script already in place and the fact there are like 42 million init systems for *NIX these days, I'd like to change the "switch" that turns on runit to something where runit is the default, but 'sysvinit' is also an option. I was thinking something like this:

```
default['lita']['init_system'] = 'runit'
```

That way, as folks who need systemd, upstart, smf, whatever come along, they can add their init provider and supporting files as a PR.

I'm happy to take your commit and make this change, but given you spent time on this, I wanted your opinion on the matter.

Thanks again!

Harlan

**Comment by ptqa** [comment]
@harlanbarnes Yeah, totally agree. Actually every one is using ```['init_style']``` attrubute (See [nginx](https://github.com/miketheman/nginx) or [chef-client](https://github.com/opscode-cookbooks/chef-client) cookbooks). So I've added the same attr and a little bit reworked default recipe, check updated commit and tell me if it's ok.

**Comment by harlanbarnes** [comment]
@ptqa LGTM. I'll get it merged in and pushed to Supermarket today. Thanks for the change!

**Comment by harlanbarnes** [comment]
I manually merged this and squashed in the version change, changelog and readme. It's released as 1.0.0 since a) it was breaking change and b) that was the last thing I really wanted to do it (and you made that happen!!!)

https://supermarket.chef.io/cookbooks/lita/versions/1.0.0

Thanks again for that.

**Pull request closed without merging**
